name: club_management_app
description: "KAT Club Management is a comprehensive app designed to streamline club operations, manage members, and organize events with ease and efficiency."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  page_transition: ^2.0.9
  awesome_dialog: ^3.2.1
  flutter_spinkit: ^5.0.0
  validators: ^3.0.0
  http: ^1.2.2 
  fl_chart: ^0.69.0
  get: ^4.6.5
  multi_select_flutter: ^4.0.0
  intl: ^0.18.0
  geolocator: ^13.0.2
  # jwt_decoder: ^2.0.1

  google_maps_flutter: ^2.1.1
  url_launcher: ^6.0.10
  permission_handler: ^10.0.0
  # location: ^4.4.0
# dev
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icon/
